"use client"
import './globals.css'
import '@ionic/react/css/core.css';
import '@ionic/react/css/normalize.css';

import Navbar from './navbar/page.js'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  
  return (
    
    <html  suppressHydrationWarning={true}  lang="en">
      <body suppressHydrationWarning={true} >
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
